name: Go Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.3"

      - name: Install dependencies
        run: go mod download

      - name: Run tests (skipping integration tests)
        run: go test -v ./... -skip TestTemplateGeneration_ -skip TestProjectExecution_ -skip TestFolderStructure_
        env:
          INTEGRATION_TESTS: "0"
          CI: "true"

      - name: Check code formatting
        run: |
          if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then
            echo "The following files are not formatted correctly:"
            gofmt -l .
            exit 1
          fi
