name: Lint

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.3"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.64.8
          args: --timeout=5m --skip-files=".*_test.go" --exclude-use-default=false
